# Generated by Django 4.1.7 on 2023-05-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="autor",
            name="artigos",
            field=models.ManyToManyField(to="escola.artigo"),
        ),
    ]
