# Generated by Django 4.1.7 on 2023-05-03 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0002_artigo_autor_artigos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_aplicacao", models.DateField(auto_now=True)),
                ("aprovado", models.BooleanField(default=False)),
                (
                    "artigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="escola.artigo"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="escola.autor"
                    ),
                ),
            ],
        ),
    ]
