# Generated by Django 4.1.7 on 2023-05-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0003_submissao"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="submissoes",
            field=models.ManyToManyField(
                related_name="autor_submissoes",
                through="escola.Submissao",
                to="escola.artigo",
            ),
        ),
    ]
