# Generated by Django 4.1.7 on 2023-05-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0004_autor_submissoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("DOC", "Docente"),
                    ("DIS", "Discente"),
                    ("SC", "Sem categoria"),
                ],
                default="SC",
                max_length=3,
            ),
        ),
    ]
