# Generated by Django 4.1.7 on 2023-05-04 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0005_autor_categoria"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "autores"},
        ),
        migrations.AlterModelOptions(
            name="submissao",
            options={"verbose_name": "submissão", "verbose_name_plural": "submissões"},
        ),
        migrations.AlterField(
            model_name="livro",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livros",
                to="escola.autor",
            ),
        ),
    ]
